#!/bin/bash


_codex_zip () {
    if [[ $GIT_REPO ]]
    then
        echo "https://github.com/${GIT_REPO}/archive/master.zip"
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3dhcnVzZXJib3QvUGx1Z2lucy1UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}

_library () {
    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then 
        python3 -m PyrogramCodex
    else
        python3 -m TelethonCodex
    fi
}

_starter () {
    local codepath
    codepath="Plugins.zip"
    echo "••• DOWNLOADING CODEXUSERBOT •••"
    wget -q $(_hell_zip) -O "$hellpath"
    HELLPATH=$(zipinfo -1 "$codexpath" | grep -v "/.");
    unzip -qq "$hellpath"
    rm -rf "$hellpath"
    cd $HELLPATH
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING CODEXUSERBOT •••"
    _library
}

_starter
